-- Assume tables:
-- Customers
-- customer_id, customer_name
-- Orders
-- order_id, customer_id, product_id, order_date, amount
-- Products
-- product_id, product_name, category
-- SQL JOIN + GROUP BY Questions (Set 4)
-- 1️⃣ Find total revenue generated in each category
SELECT p.category, SUM(o.amount) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category;

-- 2️⃣ Find number of orders placed each day
SELECT order_date, COUNT(order_id) AS total_orders
FROM orders
GROUP BY order_date;

-- 3️⃣ Find top selling product (by total revenue)
SELECT p.product_name, SUM(o.amount) AS total_sales
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_sales DESC
LIMIT 1;
-- 4️⃣ Find total revenue generated by each customer
SELECT c.customer_name, SUM(o.amount) AS total_revenue
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

-- 5️⃣ Find customers who placed more than 3 orders
SELECT c.customer_name, COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
HAVING COUNT(o.order_id) > 3;

-- 6️⃣ Find total number of products sold in each category
SELECT p.category, COUNT(o.product_id) AS products_sold
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category;

-- 7️⃣ Find average purchase amount per customer
SELECT c.customer_name, AVG(o.amount) AS avg_purchase
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name;

-- 8️⃣ Find categories with total revenue greater than 10000
SELECT p.category, SUM(o.amount) AS total_revenue
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.category
HAVING SUM(o.amount) > 10000;

-- 9️⃣ Find number of unique customers who purchased each product
SELECT p.product_name, COUNT(DISTINCT o.customer_id) AS customers
FROM orders o
JOIN products p
ON o.product_id = p.product_id
GROUP BY p.product_name;

-- 🔟 Find customer who spent the most money
SELECT c.customer_name, SUM(o.amount) AS total_spent
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_name
ORDER BY total_spent DESC
LIMIT 1;

